import { useState } from 'react';
import { materialConsumption,type PricingMaterialLine } from '@workspace/pricing-engine';
import { api,useData,useAction,Panel,Field,Select,Notice,Heading,Loading,money } from './shared';
export function Stock(){const query=useData('/stock'),history=useData<any[]>('/production',[]);const [tab,setTab]=useState('production'),[key,setKey]=useState(()=>crypto.randomUUID()),[productId,setProductId]=useState(''),[goodUnits,setGoodUnits]=useState(1),[reason,setReason]=useState(''),[consumption,setConsumption]=useState<any[]>([]),[target,setTarget]=useState('material'),[targetId,setTargetId]=useState(''),[amount,setAmount]=useState<number|null>(null),[message,setMessage]=useState('');
  const selected=query.data?.products?.find((p:any)=>String(p.id)===productId);
  const production=useAction(async()=>api('/production','POST',{key,productId:Number(productId),goodUnits,notes:reason,consumption}));
  const movement=useAction(async()=>api('/stock/movements','POST',{key,...(target==='material'?{materialId:Number(targetId)}:{productId:Number(targetId)}),amount,reason}));
  const done=()=>{setKey(crypto.randomUUID());setMessage('Movimentação registrada. O saldo foi atualizado.');setAmount(null);};
  const choose=(value:string)=>{setProductId(value);setKey(crypto.randomUUID());const p=query.data.products.find((p:any)=>String(p.id)===value);if(!p){setConsumption([]);return;}const input=p.input;setGoodUnits(input.quantity);const hasPartial=!!input.partialRun&&input.quantity%input.piecesPerRun>0;const runs=hasPartial?Math.floor(input.quantity/input.piecesPerRun):Math.ceil(input.quantity/input.piecesPerRun);const map=new Map<number,number>();for(const l of input.materials??[])if(l.materialId)map.set(l.materialId,(map.get(l.materialId)??0)+materialConsumption(l).toNumber()*runs);if(hasPartial)for(const l of input.partialRun.materials)if(l.materialId)map.set(l.materialId,(map.get(l.materialId)??0)+materialConsumption(l).toNumber());setConsumption([...map.entries()].map(([materialId,grams])=>({materialId,grams,failedGrams:0})));};
  return <><Heading title="Estoque e produção" description="Simular e orçar não consome estoque. Confirme somente a produção realizada."/><Loading query={query}/>{message&&<Notice>{message}</Notice>}{(production.error||movement.error)&&<Notice error>{(production.error||movement.error)?.message}</Notice>}
  <div className="mb-5 grid gap-4 lg:grid-cols-2"><Panel title="Filamentos disponíveis">{query.data?.materials?.map((m:any)=><div key={m.id} className="flex justify-between border-b border-border py-3 text-sm"><span>{m.name}{m.archived?' (arquivado)':''}</span><b className={m.stockGrams<=m.lowStockThreshold?'text-orange-700':''}>{m.stockGrams.toLocaleString('pt-BR')} g</b></div>)}</Panel><Panel title="Produtos acabados">{query.data?.products?.map((p:any)=><div key={p.id} className="flex justify-between border-b border-border py-3 text-sm"><span>{p.name}</span><b>{p.stock} un.</b></div>)}</Panel></div>
  <Panel title="Registrar movimentação"><div className="mb-5 flex gap-3"><button className={`btn ${tab==='production'?'btn-blue':'btn-secondary'}`} onClick={()=>{setTab('production');setKey(crypto.randomUUID());}}>Produção concluída</button><button className={`btn ${tab==='adjust'?'btn-blue':'btn-secondary'}`} onClick={()=>{setTab('adjust');setKey(crypto.randomUUID());}}>Entrada, saída ou ajuste</button></div>
  {tab==='production'?<><div className="grid gap-4 sm:grid-cols-2"><Select label="Produto produzido" value={productId} onChange={choose} options={[{value:'',label:'Selecione'},...(query.data?.products??[]).map((p:any)=>({value:String(p.id),label:p.name}))]}/><Field numeric label="Peças aprovadas (inclua excedentes produzidos)" value={goodUnits} onChange={setGoodUnits}/></div><p className="my-4 text-xs text-muted-foreground">O consumo previsto preenche os campos abaixo. Revise com o consumo real; registre perdas por falhas separadamente. Materiais manuais precisam ser associados a um cadastro.</p>{consumption.map((line,i)=><div key={i} className="mb-3 grid gap-3 sm:grid-cols-3"><Select label="Material consumido" value={line.materialId} options={[{value:'',label:'Selecione'},...(query.data?.materials??[]).map((m:any)=>({value:String(m.id),label:m.name}))]} onChange={v=>setConsumption(consumption.map((l,j)=>i===j?{...l,materialId:Number(v)}:l))}/><Field numeric label="Consumo real em peças / suportes (g)" value={line.grams} onChange={v=>setConsumption(consumption.map((l,j)=>i===j?{...l,grams:v}:l))}/><Field numeric label="Perdas reais por falhas (g)" value={line.failedGrams} onChange={v=>setConsumption(consumption.map((l,j)=>i===j?{...l,failedGrams:v}:l))}/><button className="text-xs text-red-600" onClick={()=>setConsumption(consumption.filter((_,j)=>i!==j))}>Remover linha</button></div>)}<button className="btn btn-secondary mb-4" onClick={()=>setConsumption([...consumption,{materialId:0,grams:0,failedGrams:0}])}>+ Material consumido</button><Field label="Observações da produção" value={reason} onChange={setReason}/><button className="btn btn-primary mt-4" disabled={!productId||!consumption.length||production.isPending} onClick={()=>production.mutate(undefined,{onSuccess:done})}>Confirmar produção e movimentar estoque</button></>:<><div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo" value={target} onChange={v=>{setTarget(v);setTargetId('');}} options={[{value:'material',label:'Filamento (gramas)'},{value:'product',label:'Produto acabado (unidades)'}]}/><Select label="Cadastro" value={targetId} onChange={setTargetId} options={[{value:'',label:'Selecione'},...(query.data?.[target==='material'?'materials':'products']??[]).map((x:any)=>({value:String(x.id),label:x.name}))]}/><Field numeric label="Quantidade (+ entrada / − saída)" value={amount} onChange={setAmount}/><Field label="Justificativa / entrega" value={reason} onChange={setReason}/></div><button className="btn btn-primary mt-4" disabled={!targetId||movement.isPending} onClick={()=>movement.mutate(undefined,{onSuccess:done})}>Registrar movimentação</button></>}
  </Panel><div className="mt-5"><Panel title="Histórico de estoque"><div className="max-h-96 overflow-auto">{query.data?.movements?.map((m:any)=><div key={m.id} className="border-b border-border py-3 text-sm"><b>{m.amount>0?'+':''}{m.amount.toLocaleString('pt-BR')} {m.materialId?'g':'un.'}</b> · {m.reason}<p className="text-xs text-muted-foreground">{new Date(m.createdAt).toLocaleString('pt-BR')}</p></div>)}</div></Panel></div></>;
}
export function ImportPage(){const [preview,setPreview]=useState<any>(null),[duplicateAction,setDuplicateAction]=useState('skip'),[stockUnit,setStockUnit]=useState('skip'),[gramsPerRoll,setGramsPerRoll]=useState<number|null>(null),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('');const previous=useData<any[]>('/imports',[]);
  const upload=useAction(async(file:File)=>{if(file.size>5*1024*1024||!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('Selecione uma planilha .xlsx de até 5 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return api('/imports/preview','POST',{base64:btoa(binary)});});
  const commit=useAction(async()=>api('/imports/confirm','POST',{token:preview.token,duplicateAction,stockUnit,gramsPerRoll:gramsPerRoll??undefined,confirmFullRolls:confirmed}));
  return <><Heading title="Importar planilha" description="Confira os dados antes de confirmar. Duração e máquina devem ser preenchidas após a importação."/>{message&&<Notice>{message}</Notice>}{(upload.error||commit.error)&&<Notice error>{(upload.error||commit.error)?.message}</Notice>}<Panel title="Planilha de precificação (.xlsx)"><label className="text-sm font-semibold">Selecionar arquivo<input className="field mt-2" type="file" accept=".xlsx" disabled={upload.isPending} onChange={e=>{const file=e.target.files?.[0];if(file){setPreview(null);upload.mutate(file,{onSuccess:setPreview});}}}/></label>{upload.isPending&&<p className="mt-3">Lendo planilha…</p>}</Panel>
  {preview&&<div className="mt-5 space-y-5"><Panel title="Prévia da importação"><div className="flex flex-wrap gap-5 text-sm"><b>{preview.products.length} produtos</b><b>{preview.materials.length} filamentos</b><b>{preview.investments.length} referências de investimento</b></div>{preview.errors.length>0&&<Notice error>{preview.errors.map((e:string)=><p key={e}>{e}</p>)}</Notice>}{preview.duplicates.length>0&&<p className="my-4 text-sm text-orange-700">Nomes já existentes: {preview.duplicates.join(', ')}</p>}<div className="mt-4 max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Produto</th><th>Peso</th><th>R$/kg</th><th>Adicionais</th></tr></thead><tbody>{preview.products.map((p:any)=><tr className="border-t border-border" key={`${p.sheet}-${p.row}`}><td className="p-2">{p.name}<small className="block text-muted-foreground">{p.sheet} · linha {p.row}</small></td><td>{p.weight??'Ausente'} g</td><td>{money(p.priceKg)}</td><td>{money(p.additional)}</td></tr>)}</tbody></table></div></Panel>
  <Panel title="Como importar"><div className="grid gap-4 sm:grid-cols-2"><Select label="Produtos e materiais já existentes" value={duplicateAction} onChange={setDuplicateAction} options={[{value:'skip',label:'Ignorar duplicados'},{value:'update',label:'Atualizar e criar nova versão dos produtos'}]}/><Select label="Unidade da quantidade no estoque de filamentos" value={stockUnit} onChange={setStockUnit} options={[{value:'skip',label:'Não importar estoque de filamentos'},{value:'grams',label:'Gramas restantes'},{value:'kg',label:'Quilogramas restantes'},{value:'rolls',label:'Quantidade de rolos completos'}]}/>{stockUnit==='rolls'&&<><Field numeric label="Peso líquido de cada rolo (g)" value={gramsPerRoll} onChange={setGramsPerRoll}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo que as quantidades representam rolos completos.</label></>}</div><p className="my-4 text-xs text-muted-foreground">Rolos parcialmente usados devem ser contabilizados em gramas ou kg. Investimentos serão preservados apenas como referência, sem virar despesas recorrentes.</p><button className="btn btn-primary" disabled={commit.isPending||preview.errors.length>0} onClick={()=>commit.mutate(undefined,{onSuccess:r=>{setMessage(`Importação concluída: ${r.created??0} criados, ${r.updated??0} atualizados, ${r.skipped??0} ignorados.`);setPreview(null);}})}>Confirmar importação</button></Panel></div>}
  <div className="mt-5"><Panel title="Importações anteriores e investimentos">{previous.data?.map(p=><details key={p.id} className="mb-3 text-sm"><summary>{new Date(p.createdAt).toLocaleString('pt-BR')} · {p.payload.products?.length??0} produtos</summary>{p.payload.investments?.map((x:any,i:number)=><p className="mt-2" key={i}>{x.name}: {money(x.value)}</p>)}</details>)}</Panel></div></>;
}
