import { useEffect,useState } from 'react';
import { api,useData,useAction,Panel,Field,Notice,imageData } from './shared';
export function ExtraSettings(){const query=useData('/preferences');const [form,setForm]=useState<any>(null),[message,setMessage]=useState('');useEffect(()=>{if(query.data)setForm(query.data);},[query.data]);const save=useAction(async()=>api('/preferences','PUT',form));if(!form)return null;
  const change=(i:number,key:string,value:any)=>setForm({...form,channels:form.channels.map((c:any,j:number)=>j===i?{...c,[key]:value}:c)});
  return <div className="mt-6 space-y-5">{message&&<Notice>{message}</Notice>}{save.error&&<Notice error>{save.error.message}</Notice>}<Panel title="Identidade e propostas"><div className="grid gap-4 sm:grid-cols-2"><Field label="Dados comerciais para o PDF" value={form.companyDetails} onChange={v=>setForm({...form,companyDetails:v})}/><Field numeric label="Validade padrão dos orçamentos (dias)" value={form.quoteValidityDays} onChange={v=>setForm({...form,quoteValidityDays:v})}/><label className="text-sm">Logotipo (PNG, JPEG ou WebP até 300 KB)<input className="field mt-2" type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{try{if(e.target.files?.[0])setForm({...form,logoUrl:await imageData(e.target.files[0])});}catch(err){setMessage((err as Error).message);}}}/></label>{form.logoUrl&&<div><img className="h-20 max-w-48 object-contain" src={form.logoUrl} alt="Logotipo da empresa"/><button className="text-xs text-red-600" onClick={()=>setForm({...form,logoUrl:''})}>Remover logotipo</button></div>}</div></Panel>
  <Panel title="Canais personalizados">{form.channels.map((c:any,i:number)=><div className="mb-4 rounded-xl border border-border p-4" key={c.id}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome do canal" value={c.name} onChange={v=>change(i,'name',v)}/>{[['percentFees','Comissões (%)'],['taxPercent','Tributos informados (%)'],['desiredMargin','Margem desejada (%)'],['minimumMargin','Margem mínima (%)']].map(([k,label])=><Field key={k} numeric label={label!} value={(c[k!]??0)*100} onChange={v=>change(i,k!,v===null?null:v/100)}/>)}<Field numeric label="Taxa fixa por pedido (R$)" value={c.fixedFeePerOrder} onChange={v=>change(i,'fixedFeePerOrder',v)}/><Field numeric label="Taxa por unidade (R$)" value={c.fixedFeePerUnit} onChange={v=>change(i,'fixedFeePerUnit',v)}/></div><button className="mt-3 text-xs text-red-600" onClick={()=>setForm({...form,channels:form.channels.filter((_:any,j:number)=>j!==i)})}>Remover canal</button></div>)}<button className="btn btn-secondary" onClick={()=>setForm({...form,channels:[...form.channels,{id:crypto.randomUUID(),name:'',percentFees:0,taxPercent:0,fixedFeePerOrder:0,fixedFeePerUnit:0,desiredMargin:0,minimumMargin:0}]})}>+ Canal de venda</button><p className="mt-3 text-xs text-muted-foreground">Taxas e tributos usam o valor dos produtos como base. Preencha conforme suas condições comerciais; este cadastro não faz apuração fiscal.</p></Panel>
  <Panel title="Faixas padrão de atacado">{form.wholesaleTiers.map((t:any,i:number)=><div className="mb-3 grid grid-cols-[1fr_1fr_auto] items-end gap-3" key={i}><Field numeric label="Quantidade" value={t.quantity} onChange={v=>setForm({...form,wholesaleTiers:form.wholesaleTiers.map((t:any,j:number)=>i===j?{...t,quantity:v}:t)})}/><Field numeric label="Margem (%)" value={t.margin*100} onChange={v=>setForm({...form,wholesaleTiers:form.wholesaleTiers.map((t:any,j:number)=>i===j?{...t,margin:v===null?null:v/100}:t)})}/><button className="btn btn-quiet" onClick={()=>setForm({...form,wholesaleTiers:form.wholesaleTiers.filter((_:any,j:number)=>i!==j)})}>×</button></div>)}<button className="btn btn-secondary" onClick={()=>setForm({...form,wholesaleTiers:[...form.wholesaleTiers,{quantity:1,margin:0}]})}>+ Faixa</button></Panel><button className="btn btn-primary" disabled={save.isPending} onClick={()=>save.mutate(undefined,{onSuccess:()=>setMessage('Identidade, canais e faixas salvos.')})}>Salvar identidade e canais</button></div>;
}
export function StaleNotice(){const query=useData<any[]>('/stale-products');if(!query.data?.length)return null;return <div className="mb-5"><Notice>{query.data.length} produto(s) usam custos de referência antigos. Revise em Produtos: {query.data.slice(0,5).map(p=>p.name).join(', ')}.</Notice></div>;}
