import { useState } from 'react';
import { Link } from 'wouter';
import { calculatePricing,type PricingInput } from '@workspace/pricing-engine';
import { api,useData,useAction,Panel,Field,Select,Notice,Heading,Loading,money,percent,downloadPdf } from './shared';
export function Products(){const query=useData<any[]>('/products'),stale=useData<any[]>('/stale-products');const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[history,setHistory]=useState<any[]|null>(null),[message,setMessage]=useState('');
  const duplicate=useAction((p:any)=>api('/products','POST',{name:p.name+' (cópia)',sku:null,category:p.category,input:{...p.input,name:p.name+' (cópia)'},calculation:null}));
  const remove=useAction((id:number)=>api(`/products/${id}`,'DELETE'));
  const filtered=(query.data??[]).filter(p=>(p.name+' '+(p.sku??'')).toLocaleLowerCase().includes(search.toLocaleLowerCase())&&(!category||p.category===category));
  return <><Heading title="Produtos" description="Custos versionados. Alterações nos cadastros não reescrevem o histórico."><Link href="/calculator" className="btn btn-primary">Nova precificação</Link></Heading><Loading query={query}/>{message&&<Notice>{message}</Notice>}{(duplicate.error||remove.error)&&<Notice error>{(duplicate.error||remove.error)?.message}</Notice>}
  <div className="mb-5 grid gap-4 sm:grid-cols-2"><Field label="Buscar produto ou SKU" value={search} onChange={setSearch}/><Select label="Categoria" value={category} onChange={setCategory} options={[{value:'',label:'Todas'},...[...new Set((query.data??[]).map(p=>p.category))].map(c=>({value:c,label:c}))]}/></div>
  {!query.isLoading&&!filtered.length&&<Panel title="Nenhum produto encontrado"><p>Crie uma precificação ou importe sua planilha.</p><Link href="/import" className="mt-4 inline-block text-primary">Importar planilha</Link></Panel>}
  <div className="grid gap-4 lg:grid-cols-2">{filtered.map(p=><Panel title={p.name} key={p.id}><div className="flex gap-4">{p.input.image&&<img src={p.input.image} alt={p.name} className="h-20 w-20 rounded-lg object-cover"/>}<div><p className="text-xs text-muted-foreground">{p.category} · {p.sku||'Sem SKU'}</p><p className="mt-2">Custo/un.: <b>{money(p.calculation?.unitCost)}</b></p><p>Preço: <b>{money(p.calculation?.channels?.[0]?.recommendedPerUnit)}</b></p><p className="text-xs">{p.status==='ready'?'Precificação completa':'Preencha os dados pendentes'}</p>{stale.data?.some(s=>s.id===p.id)&&<p className="mt-2 text-xs font-bold text-orange-700">Custos de referência foram atualizados</p>}</div></div><div className="mt-4 flex flex-wrap gap-2"><Link className="btn btn-blue text-xs" href={`/calculator?product=${p.id}`}>Editar</Link><Link className="btn btn-secondary text-xs" href={`/calculator?product=${p.id}&refresh=1`}>Recalcular custos atuais</Link><button className="btn btn-secondary text-xs" disabled={duplicate.isPending} onClick={()=>duplicate.mutate(p)}>Duplicar</button><button className="btn btn-quiet text-xs" onClick={async()=>{try{setHistory(await api(`/products/${p.id}/versions`));}catch(e){setMessage((e as Error).message);}}}>Histórico</button><button className="btn btn-quiet text-xs text-red-600" disabled={remove.isPending} onClick={()=>{if(confirm(`Remover ${p.name}? Orçamentos anteriores serão preservados.`))remove.mutate(p.id);}}>Remover</button></div></Panel>)}</div>{history&&<div className="mt-5"><Panel title="Histórico de versões"><button className="btn btn-quiet" onClick={()=>setHistory(null)}>Fechar</button>{history.map(v=><div className="border-b border-border py-3 text-sm" key={v.id}><b>{new Date(v.createdAt).toLocaleString('pt-BR')}</b><p>Custo/un.: {money(v.calculation?.unitCost)} · Preço: {money(v.calculation?.channels?.[0]?.recommendedPerUnit)}</p><details><summary>Premissas e custos registrados</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(v.input,null,2)}</pre></details></div>)}</Panel></div>}</>;
}
const states=[{value:'draft',label:'Rascunho'},{value:'sent',label:'Enviado'},{value:'approved',label:'Aprovado'},{value:'rejected',label:'Recusado'},{value:'expired',label:'Expirado'}];
export function Quotes(){const query=useData<any[]>('/quotes'),products=useData<any[]>('/products'),prefs=useData('/preferences');const [open,setOpen]=useState(false),[customer,setCustomer]=useState(''),[notes,setNotes]=useState(''),[validity,setValidity]=useState(''),[discount,setDiscount]=useState<number|null>(0),[message,setMessage]=useState(''),[detail,setDetail]=useState<any>(null);
  const [items,setItems]=useState<any[]>([{productId:null,productName:'',quantity:1,unitPrice:0}]);
  const action=useAction(async()=>api('/quotes','POST',{customerName:customer||null,items,discountPercent:discount===null?null:discount/100,validUntil:validity||null,notes,status:'draft'}));
  const status=useAction(({id,status}:{id:number;status:string})=>api(`/quotes/${id}`,'PATCH',{status}));
  const setItem=(i:number,values:any)=>setItems(old=>old.map((line,j)=>i===j?{...line,...values}:line));
  return <><Heading title="Orçamentos" description="Propostas comerciais com preços preservados e PDF para o cliente."><button className="btn btn-primary" onClick={()=>{setOpen(!open);const date=new Date();date.setDate(date.getDate()+(prefs.data?.quoteValidityDays??15));setValidity(date.toISOString().slice(0,10));}}>Novo orçamento</button></Heading><Loading query={query}/>{message&&<Notice>{message}</Notice>}{(action.error||status.error)&&<Notice error>{(action.error||status.error)?.message}</Notice>}
  {open&&<Panel title="Nova proposta"><div className="grid gap-4 sm:grid-cols-2"><Field label="Cliente" value={customer} onChange={setCustomer}/><Field label="Validade" type="date" value={validity} onChange={setValidity}/></div><div className="my-5 space-y-4">{items.map((line,i)=><div className="rounded-xl border border-border p-4" key={i}><div className="grid gap-4 sm:grid-cols-2"><Select label="Produto cadastrado" value={line.productId??''} options={[{value:'',label:'Item avulso'},...(products.data??[]).filter(p=>p.status==='ready').map(p=>({value:String(p.id),label:p.name}))]} onChange={v=>{const p=products.data?.find(p=>String(p.id)===v);setItem(i,p?{productId:p.id,productName:p.name,quantity:p.input.quantity,unitPrice:p.calculation?.channels?.[0]?.recommendedPerUnit??0,input:p.input}:{productId:null,input:undefined});}}/><Field label="Descrição" value={line.productName} onChange={v=>setItem(i,{productName:v})}/><Field numeric label="Quantidade" value={line.quantity} onChange={v=>setItem(i,{quantity:v})}/><Field numeric label="Preço por unidade (R$)" value={line.unitPrice} onChange={v=>setItem(i,{unitPrice:v})}/></div>{line.input&&(()=>{let r;try{r=calculatePricing({...line.input,quantity:line.quantity,practicedUnitPrice:line.unitPrice*(1-(discount??0)/100)} as PricingInput);}catch{}const actual=r?.channels.find(c=>c.channel==='Preço praticado');return <p className={`mt-3 text-xs ${(actual?.estimatedResult??0)<0?'font-bold text-red-600':'text-muted-foreground'}`}>Resultado estimado: {money(actual?.estimatedResult)} · Margem: {percent(actual?.estimatedMargin)}{(actual?.estimatedResult??0)<0?' · Abaixo do equilíbrio':''}</p>;})()}{!line.input&&<p className="mt-2 text-xs text-muted-foreground">Item avulso: sem análise de custo e margem.</p>}{items.length>1&&<button className="mt-3 text-xs text-red-600" onClick={()=>setItems(items.filter((_,j)=>j!==i))}>Remover item</button>}</div>)}</div><button className="btn btn-secondary" onClick={()=>setItems([...items,{productId:null,productName:'',quantity:1,unitPrice:0}])}>+ Produto</button><div className="my-4 grid gap-4 sm:grid-cols-2"><Field numeric label="Desconto (%)" value={discount} onChange={setDiscount}/><Field label="Observações e condições" value={notes} onChange={setNotes}/></div><button className="btn btn-primary" disabled={action.isPending} onClick={()=>action.mutate(undefined,{onSuccess:()=>{setOpen(false);setMessage('Orçamento criado.');}})}>Salvar proposta</button></Panel>}
  <div className="mt-5 space-y-4">{query.data?.map(q=><Panel key={q.id} title={`#${q.id} · ${q.customerName||'Cliente não informado'}`}><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm">{q.productName}</p><strong className="mt-2 block text-2xl">{money(q.total)}</strong><p className="mt-2 text-xs text-muted-foreground">Validade: {q.validUntil?.slice(0,10).split('-').reverse().join('/')||'Não informada'}</p></div><div className="max-w-xs"><Select label="Status comercial" value={q.status} options={states} onChange={v=>status.mutate({id:q.id,status:v})}/><p className="mt-2 text-xs text-muted-foreground">Alterar status não envia mensagens nem movimenta estoque.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-primary text-xs" onClick={()=>downloadPdf(q.id).catch(e=>setMessage(e.message))}>Baixar PDF comercial</button><button className="btn btn-secondary text-xs" onClick={()=>downloadPdf(q.id,true).catch(e=>setMessage(e.message))}>Relatório interno</button><button className="btn btn-quiet text-xs" onClick={()=>api(`/quotes/${q.id}`).then(setDetail).catch(e=>setMessage(e.message))}>Ver detalhes</button></div></Panel>)}</div>{!query.isLoading&&!query.data?.length&&<Notice>Nenhuma proposta salva. Gere uma pela calculadora ou crie um orçamento.</Notice>}{detail&&<Panel title={`Detalhes #${detail.id}`}><button onClick={()=>setDetail(null)} className="btn btn-quiet">Fechar</button><p>{detail.notes||'Sem observações'}</p>{detail.snapshot?.items?.map((l:any,i:number)=><p className="py-2 text-sm" key={i}>{l.quantity} × {l.productName} · {money(l.lineTotal)} · Custo registrado: {money(l.calculation?.completeCost)}</p>)}</Panel>}</>;
}
