import { test,expect } from '@playwright/test';
test('Precificar, salvar, recarregar, orçar e baixar PDF',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/calculator');
  await expect(page.getByRole('heading',{name:'Nova precificação'})).toBeVisible();
  await page.getByLabel('Nome do produto',{exact:true}).fill(`Vaso ${testInfo.project.name}`);
  await page.getByRole('button',{name:'2. Materiais',exact:true}).click();
  await page.getByLabel('Filamento',{exact:true}).selectOption({label:'PLA Branco (teste)'});
  await page.getByLabel('Peso útil das peças',{exact:false}).fill('100');
  await page.getByLabel('Perda adicional',{exact:true}).selectOption('percent');
  await page.getByLabel('Quantidade de perda',{exact:false}).fill('3');
  await page.getByRole('button',{name:'3. Impressão e trabalho',exact:true}).click();
  await page.getByLabel('Impressora',{exact:true}).selectOption({label:'Impressora de teste'});
  await page.getByLabel('Horas de impressão',{exact:false}).fill('4');
  await page.getByLabel('Acabamento',{exact:false}).fill('15');
  await page.getByRole('button',{name:'4. Custos adicionais',exact:true}).click();
  await page.getByLabel('Embalagem externa',{exact:false}).fill('1,10');
  await page.getByRole('button',{name:'5. Venda e resultado',exact:true}).click();
  await expect(page.getByText('R$ 36,67',{exact:true}).first()).toBeVisible();
  await page.getByRole('button',{name:'Salvar produto',exact:true}).click();
  await expect(page.getByText('Produto salvo com uma nova versão de custo.')).toBeVisible();
  await page.getByRole('button',{name:'Gerar orçamento',exact:true}).click();
  await expect(page.getByText('Orçamento salvo. O PDF está disponível em Orçamentos.')).toBeVisible();
  await page.screenshot({path:`work/calculadora-${testInfo.project.name}.png`,fullPage:true});
  await page.goto('/products');await expect(page.getByRole('heading',{name:`Vaso ${testInfo.project.name}`,exact:true})).toBeVisible();
  await page.reload();await expect(page.getByRole('heading',{name:`Vaso ${testInfo.project.name}`,exact:true})).toBeVisible();
  await page.goto('/quotes');await expect(page.getByText(`Vaso ${testInfo.project.name}`,{exact:true})).toBeVisible();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Baixar PDF comercial'}).first().click();expect((await download).suggestedFilename()).toMatch(/orcamento-\d+\.pdf/);
  await page.goto('/stock');await expect(page.getByRole('heading',{name:'Estoque e produção'})).toBeVisible();
  await page.getByLabel('Produto produzido').selectOption({label:`Vaso ${testInfo.project.name}`});
  await page.getByRole('button',{name:'Confirmar produção e movimentar estoque'}).click();
  await expect(page.getByText('Movimentação registrada. O saldo foi atualizado.')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
test('Tema persistido e configurações acessíveis',async({page})=>{await page.goto('/settings');await expect(page.getByRole('heading',{name:'Configurações',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ativar tema escuro'}).click();await page.reload();await expect(page.locator('html')).toHaveClass(/dark/);await expect(page.getByRole('heading',{name:'Canais personalizados'})).toBeVisible();});
