import test,{after,before} from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import express from 'express';
import ExcelJS from 'exceljs';
import { emptyPricingInput,emptyMaterial } from '@workspace/pricing-engine';
process.env.DATABASE_MODE='local';process.env.LOCAL_DATABASE_PATH='memory://';
const {migrate}=await import('../../../../lib/db/src/migrate');
const {closeDatabase}=await import('@workspace/db');
const {default:router}=await import('../routes/pricing');
const {errorHandler}=await import('../app');
let server:ReturnType<ReturnType<typeof express>['listen']>,url:string;
before(async()=>{await migrate();const app=express();app.use(express.json({limit:'8mb'}));app.use((req,res,next)=>{res.locals.userId=req.headers['x-test-principal']||'account-a';next();});app.use('/api',router);app.use(errorHandler);server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));url=`http://127.0.0.1:${(server.address() as any).port}/api`;});
after(async()=>{await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));await closeDatabase();});
async function request(path:string,method='GET',body?:any,user='account-a'):Promise<{status:number;body:any}>{const r=await fetch(url+path,{method,headers:{'Content-Type':'application/json','x-test-principal':user},body:body?JSON.stringify(body):undefined});const json=r.status===204?null:r.headers.get('content-type')?.includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer());return {status:r.status,body:json};}
const material={name:'PLA Branco',type:'PLA',brand:'Marca',color:'Branco',supplier:'Loja',netWeightGrams:1000,purchaseValue:100,allocatedFreight:0,stockGrams:1000,lowStockThreshold:100,archived:false};
const productionInput=()=>({...emptyPricingInput(),name:'Vaso',materials:[{...emptyMaterial(),name:'PLA',costPerGram:.1,usefulGrams:100}],printMinutes:60,averagePowerWatts:100,energyRate:1,hourlyLaborRate:20,monthlyFixedExpenses:0,productiveHoursMonthly:0,desiredMargin:.3});
test('Fluxo persistente, isolamento entre contas, estoque idempotente e propostas',async()=>{
  const m=await request('/materials','POST',material);assert.equal(m.status,201,JSON.stringify(m.body));const input={...productionInput(),materials:[{...productionInput().materials[0]!,materialId:m.body.id}]};
  const product=await request('/products','POST',{name:'Vaso',sku:'V1',category:'Decoração',input,calculation:null});assert.equal(product.status,201,JSON.stringify(product.body));assert.equal(product.body.calculation.complete,true);
  assert.equal((await request('/products','GET',undefined,'account-b')).body.length,0);
  assert.equal((await request(`/products/${product.body.id}`,'GET',undefined,'account-b')).status,404);
  assert.equal((await request('/calculations','POST',input,'account-b')).status,404);
  const calc=await request('/calculations','POST',{...input,desiredMargin:.5});assert.equal(calc.status,200);assert.equal(calc.body.channels[0].recommendedPerUnit,20.2);
  const q=await request('/quotes','POST',{customerName:'Cliente',productName:'Vaso',quantity:1,unitPrice:20,input,status:'draft',validUntil:'2026-12-31',notes:'Prazo de produção: 5 dias'});assert.equal(q.status,201,JSON.stringify(q.body));assert.equal(q.body.snapshot.engineVersion,'2.0.0');
  const stockBefore=await request('/stock');assert.equal(stockBefore.body.materials[0].stockGrams,1000);
  const job={key:randomUUID(),productId:product.body.id,goodUnits:1,notes:'Produção teste',consumption:[{materialId:m.body.id,grams:100,failedGrams:5}]};
  const first=await request('/production','POST',job);assert.equal(first.status,201,JSON.stringify(first.body));assert.equal((await request('/production','POST',job)).body.replayed,true);
  assert.equal((await request('/production','POST',{...job,goodUnits:2})).status,409);
  const stock=await request('/stock');assert.equal(stock.body.materials[0].stockGrams,895);assert.equal(stock.body.products[0].stock,1);
  const fail=await request('/production','POST',{...job,key:randomUUID(),consumption:[{materialId:m.body.id,grams:10000,failedGrams:0}]});assert.equal(fail.status,409);assert.equal((await request('/stock')).body.materials[0].stockGrams,895);
  const delivery={key:randomUUID(),productId:product.body.id,amount:-1,reason:'Entrega ao cliente'};assert.equal((await request('/stock/movements','POST',delivery)).status,201);assert.equal((await request('/stock/movements','POST',delivery)).body.replayed,true);assert.equal((await request('/stock')).body.products[0].stock,0);
  assert.equal((await request('/stock/movements','POST',{...delivery,key:randomUUID()})).status,409);
  const changed=await request(`/materials/${m.body.id}`,'PATCH',{...material,purchaseValue:150,stockGrams:895});assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal((await request(`/quotes/${q.body.id}`)).body.snapshot.items[0].input.materials[0].costPerGram,.1);
  const versions=await request(`/products/${product.body.id}/versions`);assert.equal(versions.body.length,1);
  const pdf=await request(`/quotes/${q.body.id}/pdf`);assert.equal(pdf.status,200);assert.equal(pdf.body.subarray(0,4).toString(),'%PDF');assert.equal((await request(`/quotes/${q.body.id}/pdf`,'GET',undefined,'account-b')).status,404);
  assert.equal((await request(`/quotes/${q.body.id}`,'PATCH',{status:'approved'})).status,200);
  assert.equal((await request(`/products/${product.body.id}`,'DELETE')).status,409);
  const refreshed=await request(`/products/${product.body.id}/current-input`);assert.equal(refreshed.body.input.materials[0].costPerGram,.15);
});
test('Importação com vírgula, fórmulas vazias ignoradas, repetição e isolamento',async()=>{
  const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('PRECIFICAÇÃO PRODUTOS DIVERSOS');sheet.getCell('C6').value='Apito';sheet.getCell('D6').value='2,15';sheet.getCell('I6').value=95;sheet.getCell('J6').value=0;sheet.getCell('H6').value=' PLA ';sheet.getCell('K7').value={formula:'1+1',result:2};const investment=book.addWorksheet('INVESTIMENTO INICIAL');investment.getCell('A4').value='Máquina';investment.getCell('B4').value=3000;
  const buffer=await book.xlsx.writeBuffer();const preview=await request('/imports/preview','POST',{base64:Buffer.from(buffer).toString('base64')});assert.equal(preview.status,200,JSON.stringify(preview.body));assert.equal(preview.body.products.length,1);assert.equal(preview.body.products[0].weight,2.15);assert.equal(preview.body.products[0].material,'PLA');
  const payload={token:preview.body.token,duplicateAction:'skip',stockUnit:'skip'};assert.equal((await request('/imports/confirm','POST',payload,'account-b')).status,404);
  const imported=await request('/imports/confirm','POST',payload);assert.equal(imported.status,200,JSON.stringify(imported.body));assert.equal(imported.body.created,1);assert.equal((await request('/imports/confirm','POST',payload)).body.replayed,true);
  const preview2=await request('/imports/preview','POST',{base64:Buffer.from(buffer).toString('base64')});assert.equal(preview2.body.duplicates[0],'Apito');const again=await request('/imports/confirm','POST',{...payload,token:preview2.body.token});assert.equal(again.body.skipped,1);
  const list=await request('/products');assert.equal(list.body.filter((p:any)=>p.name==='Apito').length,1);assert.equal(list.body.find((p:any)=>p.name==='Apito').status,'incomplete');
});
test('Proposta com vários itens, desconto e validação',async()=>{const q=await request('/quotes','POST',{customerName:null,items:[{productName:'A',quantity:3,unitPrice:12.5},{productName:'B',quantity:2,unitPrice:10}],discountPercent:.1,validUntil:null,notes:''});assert.equal(q.status,201);assert.equal(q.body.total,51.75);assert.equal((await request('/quotes','POST',{customerName:null,items:[],validUntil:null,notes:''})).status,400);});
